// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmDIXyi_LlacgoCTtVok7rc897ClNH2qA',
    appId: '1:276488656818:web:18a69e2d020d5b6f48f6ab',
    messagingSenderId: '276488656818',
    projectId: 'neuroconecta-e5bae',
    authDomain: 'neuroconecta-e5bae.firebaseapp.com',
    storageBucket: 'neuroconecta-e5bae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMNC_JaimRvpdk2ExiQBvbU2aCN8nUfmA',
    appId: '1:276488656818:android:be621892c511274448f6ab',
    messagingSenderId: '276488656818',
    projectId: 'neuroconecta-e5bae',
    storageBucket: 'neuroconecta-e5bae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfTtkn4Ww-9CFbPi31G1Jl8o1eeSsgd8M',
    appId: '1:276488656818:ios:f68c056f8624dc8048f6ab',
    messagingSenderId: '276488656818',
    projectId: 'neuroconecta-e5bae',
    storageBucket: 'neuroconecta-e5bae.firebasestorage.app',
    iosBundleId: 'com.example.appNeuroconecta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfTtkn4Ww-9CFbPi31G1Jl8o1eeSsgd8M',
    appId: '1:276488656818:ios:f68c056f8624dc8048f6ab',
    messagingSenderId: '276488656818',
    projectId: 'neuroconecta-e5bae',
    storageBucket: 'neuroconecta-e5bae.firebasestorage.app',
    iosBundleId: 'com.example.appNeuroconecta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmDIXyi_LlacgoCTtVok7rc897ClNH2qA',
    appId: '1:276488656818:web:f832bb514db58cf548f6ab',
    messagingSenderId: '276488656818',
    projectId: 'neuroconecta-e5bae',
    authDomain: 'neuroconecta-e5bae.firebaseapp.com',
    storageBucket: 'neuroconecta-e5bae.firebasestorage.app',
  );
}
